### ISSUE TITLE
Cannot compile specimen

### ISSUE THREAD

**Issue by psiotwo** [mikkelee/latex-pua#3]
When trying to compile (lualatex --synctex=1 --interaction=nonstopmode specimen.tex) the specimen.tex using lualatex 1.10.0, I get

"Package fontspec Error: The font "PalemonasMUFI" cannot be found."

Maybe I am missing some bit of configuration?

**Comment by mikkelee** [comment]
Have you installed the font on your system? It is available here:
https://mufi.info/m.php?p=mufi&i=972
