### ISSUE TITLE
LaTeX does not find csvsimple.tmp.patch.tex

### ISSUE THREAD

**Issue by Alexander-Wilms** [mikkelee/latex-pua#4]
The openSUSE downstream package doesn't include the [csvsimple.tmp.patch.tex](https://github.com/mikkelee/latex-pua/blob/master/latex/csvsimple.tmp.patch.tex), which I reported here: https://bugzilla.opensuse.org/show_bug.cgi?id=1208673

But even if I copy the file to `/usr/share/texmf/tex/latex/unicode-alphabets/`, I still get the error `File 'csvsimple.tmp.patch' not found. \input{csvsimple.tmp.patch}`

However, it works when I copy the patch to the directory of the .tex file I'm compiling.

**Comment by mikkelee** [comment]
Thanks for the report! I'll look into it.

**Comment by mikkelee** [comment]
The patch should no longer be needed, cf. T-F-S/csvsimple/issues/7#issuecomment-856052240

I have submitted a new version to CTAN

**Comment by Alexander-Wilms** [comment]
Thanks, will do.

**Comment by mikkelee** [comment]
The new version is on CTAN: https://www.ctan.org/pkg/unicode-alphabets

**Comment by Alexander-Wilms** [comment]
I can confirm that this fixes the issue for me. Thanks!
